---
- hosts: all
  become: yes
  vars:
    postgresql_version: "{{ lookup('vars', 'postgresql_version_' + ansible_os_family | lower) }}"
    postgresql_package_name: "{{ lookup('vars', 'postgresql_package_name_' + ansible_os_family | lower) }}"
    postgresql_data_directory: "{{ lookup('vars', 'postgresql_data_directory }}"
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: sudo or not
      command: whoami

    - name: Install PostgreSQL on Ubuntu
      apt:
        name: "{{ postgresql_package_name }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install PostgreSQL on Arch Linux
      pacman:
        name: "{{ postgresql_package_name }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"
    
    - name: Create data directory
      file:
        path: "{{ postgresql_data_directory }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Check if PostgreSQL data directory is initialized
      stat:
        path: "{{ postgresql_data_directory }}/PG_VERSION"
      register: pg_data_dir

    - name: Initialize PostgreSQL data directory (Arch Linux)
      command: "su -l postgres -c \"initdb --locale=C.UTF-8 --encoding=UTF8 -D '{{ postgresql_data_directory }}'\""
      when:
        - ansible_os_family == "Archlinux"
        - not pg_data_dir.stat.exists
  
    - name: Healthcheck PostgreSQL on Ubuntu
      service:
        name: postgresql
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Healthcheck PostgreSQL on Arch Linux
      systemd:
        name: postgresql
        state: started
        enabled: yes
      when: ansible_os_family == "Archlinux"