all:
  children:
    debian:
      hosts:
        darlene: 
          ansible_host: "{{ lookup('env', 'REMOTE_HOST')}}"
          ansible_user: "{{ lookup('env', 'REMOTE_USER')}}"
          ansible_ssh_private_key_file: "~/.ssh/gh_key"
        darlene-vm:
          ansible_host: darlene-vm
          ansible_user: observer
    arch:
      hosts:
        zero: 
          ansible_host: zero
          ansible_user: mlnxl
