webservers:
  hosts:
    darlene: 
      ansible_host: darlene.deadbeef.rest
      ansible_user: observer
    darlene-vm:
      ansible_host: darlene-vm
      ansible_user: observer
    zero: 
      ansible_host: zero
      ansible_user: mlnxl
