all:
  children:
    debian:
      hosts:
        darlene: 
          ansible_host: darlene.deadbeef.rest
          ansible_user: observer
        darlene-vm:
          ansible_host: darlene-vm
          ansible_user: observer
    arch:
      hosts:
        zero: 
          ansible_host: zero
          ansible_user: mlnxl
